### ISSUE TITLE
Code and File Structure Cleanup

### ISSUE THREAD

**Issue by vpodk** [Datamart/Komito-CDN#3]
Remove all outdated and unused files and folders.

- [x] [mocks](https://github.com/Datamart/Komito-CDN/tree/master/mocks);
- [x] versions (v?);
- [x] code.

**Comment by vpodk** [comment]
@deadproxor Do you need the "[mocks](https://github.com/Datamart/Komito-CDN/tree/master/mocks)" folder?

**Comment by deadproxor** [comment]
@vpodk No. Will remove it.

**Comment by vpodk** [comment]
@deadproxor Thank you.
